name: 'rossmann'
version: '1.0.0'
config-version: 2

profile: 'rossmann'

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  rossmann:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
