"""
Seed the source MySQL OLTP database with Rossmann-schema data.

Reads data/train.csv + data/store.csv (generated by generate_data.py),
maps the public Rossmann CSV columns to the snake_case OLTP schema, and loads
them into the `sales` and `store` tables. Idempotent: truncates before load.

Runs both from the host (defaults to localhost) and inside the compose `seed`
service (MYSQL_HOST=mysql). Waits for MySQL to accept connections.
"""
from __future__ import annotations

import os
import sys
import time
from pathlib import Path

import pandas as pd
from sqlalchemy import create_engine, text

DATA_DIR = Path(os.environ.get("DATA_DIR", Path(__file__).resolve().parents[1] / "data"))

SALES_COL_MAP = {
    "Store": "store_id",
    "DayOfWeek": "day_of_week",
    "Date": "sale_date",
    "Sales": "sales",
    "Customers": "customers",
    "Open": "open_flag",
    "Promo": "promo",
    "StateHoliday": "state_holiday",
    "SchoolHoliday": "school_holiday",
}
STORE_COL_MAP = {
    "Store": "store_id",
    "StoreType": "store_type",
    "Assortment": "assortment",
    "CompetitionDistance": "competition_distance",
}


def mysql_engine():
    host = os.environ.get("MYSQL_HOST", "localhost")
    port = os.environ.get("MYSQL_PORT", "3306")
    user = os.environ.get("MYSQL_USER", "rossmann")
    pw = os.environ.get("MYSQL_PASSWORD", "rossmann_pw")
    db = os.environ.get("MYSQL_DATABASE", "rossmann")
    return create_engine(
        f"mysql+pymysql://{user}:{pw}@{host}:{port}/{db}", pool_pre_ping=True
    )


def wait_for_mysql(engine, attempts: int = 30, delay: int = 3):
    for i in range(1, attempts + 1):
        try:
            with engine.connect() as c:
                c.execute(text("SELECT 1"))
            print(f"MySQL reachable (attempt {i}).")
            return
        except Exception as exc:  # noqa: BLE001
            print(f"  waiting for MySQL ({i}/{attempts}): {exc.__class__.__name__}")
            time.sleep(delay)
    raise SystemExit("MySQL did not become available in time.")


def main():
    train_path = DATA_DIR / "train.csv"
    store_path = DATA_DIR / "store.csv"
    if not train_path.exists() or not store_path.exists():
        raise SystemExit(f"Missing data files in {DATA_DIR}; run generate_data.py first.")

    sales = pd.read_csv(train_path).rename(columns=SALES_COL_MAP)
    store = pd.read_csv(store_path).rename(columns=STORE_COL_MAP)
    sales["state_holiday"] = sales["state_holiday"].astype(str)

    engine = mysql_engine()
    wait_for_mysql(engine)

    with engine.begin() as conn:
        conn.execute(text("TRUNCATE TABLE sales"))
        conn.execute(text("TRUNCATE TABLE store"))

    store.to_sql("store", engine, if_exists="append", index=False)
    sales.to_sql(
        "sales", engine, if_exists="append", index=False, chunksize=5000, method="multi"
    )

    with engine.connect() as conn:
        n_sales = conn.execute(text("SELECT COUNT(*) FROM sales")).scalar()
        n_store = conn.execute(text("SELECT COUNT(*) FROM store")).scalar()
    print(f"Seeded MySQL: sales={n_sales:,} rows, store={n_store:,} rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
